version: "2.4"

services:
  influxdb:
    image: influxdb:2.9
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: "${INFLUX_PASS}"
      DOCKER_INFLUXDB_INIT_ORG: car-monitor
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry
      DOCKER_INFLUXDB_INIT_TOKEN: "${INFLUX_TOKEN}"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASS}"
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_DASHBOARDS_JSON_PATH: /etc/grafana/provisioning/dashboards

  telegraf:
    image: telegraf:1.33
    container_name: telegraf
    restart: unless-stopped
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      HOST_PROC: /proc
      HOST_SYS: /sys
      HOST_ETC: /etc
      MIKROTIK_PASS: "${MIKROTIK_PASS}"
